### ISSUE TITLE
No added user nx after calling nxsetup

### ISSUE THREAD

**Issue by Djelff** [dimbor-ru/freenx-server#1]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

root@addm-VirtualBox:/usr/bin# nxsetup 
------> You did select no action.
        FreeNX guesses that you want to _install_ the server.
        Type "y" to abort the installation at this point in time.
        "N" is the default and continues installation.
        Use "/usr/bin/nxsetup --help" to get more detailed help hints.

 Do you want to abort now? [y/N] 

------> It is recommended that you use the NoMachine key for
        easier setup. If you answer "y", FreeNX creates a custom
        KeyPair and expects you to setup your clients manually. 
        "N" is default and uses the NoMachine key for installation.

 Do you want to use your own custom KeyPair? [y/N] 
Setting up /etc/nxserver ...done
Setting up /var/lib/nxserver/db ...done
Setting up /var/log/nxserver.log ...done
Setting up known_hosts and authorized_keys2 ...done
Setting up permissions ...chown: неверный пользователь: «nx:root»

**Comment by dimbor-ru** [comment]
Thanks for your first comment. Adding of user nx to the system is now performed after installing the package (freenx-server.postinst). In the near future I’ll duplicate this in nxsetup script.

**Comment by dimbor-ru** [comment]
Done. Please check [it](https://github.com/dimbor-ru/freenx-server/tree/check_nx_user_group).

**Comment by uli42** [comment]
I guess you mean freenx-server.postinst...

**Comment by dimbor-ru** [comment]
It is right. Thanks. Now I will correct my comment.
