### ISSUE TITLE
Not found sessions.sq3 after nxsetup or nxserver --cleanup

### ISSUE THREAD

**Issue by Djelff** [dimbor-ru/freenx-server#2]
root@addm-VirtualBox:/var/lib/nxserver/db# nxserver --restart
/usr/bin/nxserver: строка 178: /var/lib/nxserver/db/sessions.sq3: Нет такого файла или каталога
chown: невозможно получить доступ к '/var/lib/nxserver/db/sessions.sq3': Нет такого файла или каталога
chmod: невозможно получить доступ к '/var/lib/nxserver/db/sessions.sq3': Нет такого файла или каталога
NX> 100 NXSERVER - Version 3.5.0-0.2-CE OS (GPL, using backend: 3.5.99.22)
NX> 123 Service stopped
NX> 122 Service started
NX> 999 Bye

root@addm-VirtualBox:/var/lib/nxserver/db# nxserver --cleanup
/usr/bin/nxserver: строка 178: /var/lib/nxserver/db/sessions.sq3: Нет такого файла или каталога
chown: невозможно получить доступ к '/var/lib/nxserver/db/sessions.sq3': Нет такого файла или каталога
chmod: невозможно получить доступ к '/var/lib/nxserver/db/sessions.sq3': Нет такого файла или каталога
NX> 100 NXSERVER - Version 3.5.0-0.2-CE OS (GPL, using backend: 3.5.99.22)
/usr/bin/nxserver: строка 178: /var/lib/nxserver/db/sessions.sq3: Нет такого файла или каталога
NX> 500 Error: No running sessions found.
NX> 999 Bye

**Comment by Djelff** [comment]
Is need to check installed sqlite3, expect and other before executing nxsetup
And autorun nxsetup --check after nxsetup

**Comment by dimbor-ru** [comment]
I drop "set -e" string in nxsetup. And nxserver on first start could to create session db  - [(here)](https://github.com/dimbor-ru/freenx-server/tree/check_nx_user_group)
