### ISSUE TITLE
Is need to exclude nxgialog since it is included in nx-libs

### ISSUE THREAD

**Issue by Djelff** [dimbor-ru/freenx-server#4]
root@srv-ubuntu:/usr/src/NXServer# dpkg -i ./freenx-server_1.0.0_amd64.deb                                                                                                 
(Чтение базы данных … на данный момент установлено 314695 файлов и каталогов.)
Подготовка к распаковке …/freenx-server_1.0.0_amd64.deb …
Распаковывается freenx-server (1.0.0) …
dpkg: ошибка при обработке архива ./freenx-server_1.0.0_amd64.deb (--install):
 попытка перезаписать «/usr/bin/nxdialog», который уже имеется в пакете nxdialog 2:3.5.99.22-0
Обрабатываются триггеры для libc-bin (2.23-0ubuntu11) …
Обрабатываются триггеры для dbus (1.10.6-1ubuntu3.5) …
При обработке следующих пакетов произошли ошибки:
 ./freenx-server_1.0.0_amd64.deb

**Comment by dimbor-ru** [comment]
nxdialog has been renamed to [nxdialog.freenx](https://github.com/dimbor-ru/freenx-server/commit/b4ca98acd364f571dac1f7aec1258e66f3305ed8)
However, it is called from 4-5 places in the code. It is necessary to check whether the analogue works.
