### ISSUE TITLE
ubuntu 18.04 Session did not start

### ISSUE THREAD

**Issue by zld932** [dimbor-ru/freenx-server#7]
Hello, I use freenx-server from `https://unixforum.org/up/nxman/freenx-server_2.1.1_amd64.deb` to build a nxserver for ubuntu 18.04, and use `nxclient-3.5.0-9.exe` for windows. The commands used for building nxserver are as follows.
``` bash
wget https://unixforum.org/up/nxman/freenx-server_2.1.1_amd64.deb
dpkg -i ./freenx-server_2.1.1_amd64.deb
apt install -f
dpkg -i ./freenx-server_2.1.1_amd64.deb
echo PubkeyAcceptedKeyTypes=+ssh-dss >> /etc/ssh/sshd_config
echo "AllowUsers nx zld932" >> /etc/ssh/sshd_config
systemctl restart sshd
nxsetup --install --auto
```
I want to use `mate` for desktop environment. But I can't start mate-session. The logs from nxclient are as follows.
```
NX> 203 NXSSH running with pid: 16272
NX> 285 Enabling check on switch command
NX> 285 Enabling skip of SSH config files
NX> 285 Setting the preferred NX options
NX> 200 Connected to address: 192.168.0.177 on port: 22
NX> 211 The authenticity of host '192.168.0.177 (192.168.0.177)' can't be established.
RSA key fingerprint is 
Are you sure you want to continue connecting (yes/no)? 
Warning: Permanently added '192.168.0.177' (RSA) to the list of known hosts.
NX> 202 Authenticating user: nx
NX> 208 Using auth method: publickey
/usr/bin/xauth:  file /var/lib/nxserver/home//.Xauthority does not exist
HELLO NXSERVER - Version 3.5.0-2.1.1-CE OS (GPL, using backend: 3.5.99.16)
NX> 105 hello NXCLIENT - Version 3.5.0
NX> 134 Accepted protocol: 3.5.0
NX> 105 SET SHELL_MODE SHELL
NX> 105 SET AUTH_MODE PASSWORD
NX> 105 login
NX> 101 User: zld932
NX> 102 Password: 
/usr/share/freenx-server/nxfuncs: line 387: declare: `=': not a valid identifier
NX> 103 Welcome to: zld932-VirtualBox user: zld932
NX> 105 listsession --user="zld932" --status="suspended,running" --geometry="3840x2160x32+render" --type="unix-application"
NX> 127 Sessions list of user 'zld932' for reconnect:

Display Type             Session ID                       Options  Depth Screen         Status      Session Name
------- ---------------- -------------------------------- -------- ----- -------------- ----------- ------------------------------


NX> 148 Server capacity: not reached for user: zld932
NX> 105 startsession  --virtualdesktop="1" --application="/usr/bin/mate-session" --link="adsl" --backingstore="1" --encryption="1" --cache="16M" --images="64M" --shmem="1" --shpix="1" --strict="0" --composite="1" --media="0" --session="ubuntu" --type="unix-application" --geometry="1024x768" --client="winnt" --keyboard="pc105/us" --screeninfo="1024x768x32+render"

NX> 1004 Error: Session did not start.
NX> 596 Session start failed.
NX> 999 Bye
NX> 280 Exiting on signal: 15
```
Hope you can help me. Thank you!

**Comment by dimbor-ru** [comment]
> /usr/share/freenx-server/nxfuncs: line 387: declare: `=': not a valid identifier

This error usually occurs when shell of user (nx or zld932) is '/bin/sh'. Must be '/bin/bash'.
Check please  /etc/passwd.
zld932 must also be in the group 'users'

Small note: In sshd_config enough to write "AllowUsers nx". freenx users don't use ssh authentication now.

If the problem persists send please output of 'nxsetup --mkdb'

**Comment by zld932** [comment]
Thank you for your reply.
I didn't add zld932 to the `user` group

**Comment by zld932** [comment]
Thank you for your reply.
I didn't add zld932 to the `users` group.
Now the session is started.

**Comment by dimbor-ru** [comment]
- [ ] It is required to add a separate warning to the nxserver code if the user does not have system rights to start the session.

**Comment by zld932** [comment]
Another small question is `copy` and `paste` shortcuts in terminal or text editor.
When I want to copy some words in terminal, I use `ctrl+shift+c`. the terminal shows 
```
zld932@zld932:~$ ^C
zld932@zld932:~$ ^C
zld932@zld932:~$ ^C
zld932@zld932:~$ 
```
And when I want to paste some words in terminal, I use `ctrl+shift+v`. the terminal shows nothing but when I type `Return`, the next input shows
```
zld932@zld932:~$ ^M
: command not found
zld932@zld932:~$ вафываыфваыфв
```

**Comment by dimbor-ru** [comment]
It so happened, I don't use these key combinations in the terminal. (I use Ctrl+Ins/Shift+Ins and they are ok under my xfce4-terminal.) I suspect this behavior is related to the x-terminal (Xterm/gnome-terminal/???) settings on your server.

**Comment by zld932** [comment]
Thank you. I didn't change the settings of x-terminal. Perhaps it is releated to the system settings.
